### ISSUE TITLE
configuration 

### ISSUE THREAD

**Issue by troncar** [open-pay/openpay-magento2-cards#1]
Hi,
I'm getting this error message when saving my configuration:

"Something went wrong while saving this configuration: Could not connect with webhook service, verify URL"

**Comment by fedebalderas** [comment]
Este error se puede deber a lo siguiete:

Cuando se instala el módulo, automáticamente se crea un webhook para recibir notificaciones de pagos. Si te encuentras trabajando en un ambiente local (localhost). El servicio se de Openpay que valida que la URL del webhook exista por obvias no alcanza el aplicativo y arroja este error. 


Saludos!

**Comment by troncar** [comment]
@fedebalderas Me manda el siguiente error
Something went wrong while saving this configuration: Expected 200 response from http://.../openpay/index/webhook but was 503 - Service Unavailable 

La url me manda el siguiente mensaje:
There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 1324383305180

Dentro del log de errores:
"Notice: Trying to get property of non-object in /var/www/..../vhost/app/code/Openpay/Banks/Controller/Index/Webhook.php on line 40" /var/www/....../vhost/app/code/Openpay/Banks/Controller/Index/Webhook.php(40): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '....', 40, Array)

**Comment by fedebalderas** [comment]
Que tal @troncar , 

Pero esto ocurre cuando guardas las configuraciones del módulo?? Podrías adjuntar impresiones de pantalla de esto de favor. 

De igual forma no se si pudieras revisar tu log de Openpay (dentro del menú izquierdo del dashboard, es la última opción) para ver el error que arroja de este lado también.

Quedo en espera de tus comentarios

Saludos!

**Comment by troncar** [comment]
@fedebalderas 
en log de OpenPay me manda lo siguiente:
{
    "category": "request",
    "description": "Expected 200 response from http://.../openpay/index/webhook but was 500 - Internal Server Error",
    "http_code": 502,
    "error_code": 6003,
    "request_id": "4a0f95e0-f2fa-4295-b686-afc09be68cb6"
}

**Comment by fedebalderas** [comment]
Pareciera que el problema es que no se manda el host, por ende no encuentra la URL, dejame revisarlo y subo la corrección.

Que versión de PHP es tu servidor?


Saludos!

**Comment by troncar** [comment]
Es 5.5.9

**Comment by fedebalderas** [comment]
Podrías agregar una impresión de pantalla de tu log de Openpay, para poder ver la petición... Te adjunto una impresión de pantalla de como debe de ser la petición (marca error porque es un ambiente local)
![screen shot 2016-04-28 at 6 24 32 pm](https://cloud.githubusercontent.com/assets/5208431/14904564/a0695966-0d6e-11e6-95cb-ee8b9322ed70.png)

**Comment by fedebalderas** [comment]
@troncar , podrías pasarme el host de tu plataforma para simular desde Postman una petición de verificación y ver si se puede alcanzar.


Saludos!

**Comment by troncar** [comment]
![info_logopen](https://cloud.githubusercontent.com/assets/17935106/14905068/022e63d6-0d73-11e6-81cd-07f3d2adbc38.PNG)

**Comment by fedebalderas** [comment]
Hice la prueba y si alcanza el endpoint de tu servidor, el problema es cuando quiere obtener la propiedad "type" del objeto que se te envía.

No se si puedas darme acceso FTP a tu servidor para ubicar el problema como tal y darle solución.


Saludos!

**Comment by humbertoleite** [comment]
Hola,

Estoy tenendo el mismo fallo. @troncar has solucionado?

saludos!

**Comment by troncar** [comment]
Si, hace unos meses pude hacer las pruebas bien.

**Comment by edcg** [comment]
Estoy teniendo el mismo problema. ¿Cómo lo solucionaron?

**Comment by patrickoliveras** [comment]
Que tal! Si van a cerrar estos Issues sería bastante útil que publicaran la manera en que lo resolvieron. Cómo solucionaron este problema?

**Comment by patrickoliveras** [comment]
Usando el log (https://magento.stackexchange.com/questions/92434/magento-2-replacement-for-magelog-method/92442#92442), hice una solicitud a mano desde el dashboard de Openpay y capturé el código de verificación, ya que cuando realizaba la configuración desde el admin del Módulo, el json llegaba vacío 
![image](https://user-images.githubusercontent.com/11946875/36004496-a223c2f6-0cf8-11e8-9d40-31646506b6b5.png)

**Comment by fedebalderas** [comment]
@patrickoliveras  El plugin registra automáticamente el webhook, tu no debes de darlo de alta en el dashboard, de hecho hay un problema que sucede al registrar primero el webhook en el dashboard de Openpay porque cuando el plugin lo intenta registrar este detecta que ya existe (aunque no este activado) y no lo activa.

Si tu webhook no esta activado, borralo y después en el backoffice de tu tienda dale "Guardar" a la configuración del plugin (aunque no modifiques nada), esto hará el intento de registrar tu webhook.

Ahora bien, también debes verificar si en realidad tu plugin apunta a la rama de dev-master en el composer.json y de no ser así, modificarlo y hacer un composer update.

**Comment by patrickoliveras** [comment]
Sí, cuando estaba revisando las causas fue la primera suposición que hice (el que estuviera registrado el webhook). Así que en todos los intentos (haciéndolo con 'Guardar' en el panel de métodos de pago) revisaba que no estuviera registrado ya en el Dashboard de openpay.

Hasta donde sé, el método de pago funciona a pesar de que marque que el webhook existe. Y desde que hice el webhook con confirmación manual, he podido realizar los pagos en los tres métodos de su servicio.

Y siempre he estado trabajando con dev-master.

**Comment by patrickoliveras** [comment]
Para hacer la confirmación manual, logueé el json de las solicitudes que se hacían a /openpay/index/webhook

**Comment by patrickoliveras** [comment]
![image](https://user-images.githubusercontent.com/11946875/36040406-f8611906-0d8a-11e8-98aa-996798f5d157.png)
Aquí los primeros dos son las solicitudes que se hicieron a la URL del webhook con 'Guardar'. Ambos verificando que no estuviera registrado ya un webhook. El último es de cuando lo hice manualmente.

**Comment by fedebalderas** [comment]
@patrickoliveras Cuando la validación del webhook se hace a través de la API no regresa nada, por eso no pinta nada, únicamente cuando se hace forma manual. Y si, los métodos de pago deben de funcionar independientemente de si el webhook este registrado o no, esto únicamente es para actualizar el estatus de los pagos offline.

Pero entonces ya no sé cual es tu problema si ya tienes inclusive el código de verificación si lo hiciste de forma manual.

**Comment by patrickoliveras** [comment]
Lo de la solución manual lo estoy poniendo aquí para compartirlo, ya que usando "Guardar" da error en app/code/Openpay/Banks/Controller/Index/Webhook.php línea 40, que intenta evaluar la propiedad type de un json que no lo tiene (el que genera la plataforma {}).

**Comment by fedebalderas** [comment]
@patrickoliveras  Podrías compartirme en screenshot de como tienes esta clase: app/code/Openpay/Banks/Controller/Index/Webhook.php

**Comment by patrickoliveras** [comment]
@fedebalderas Diste en el clavo! Jaja

Estaba probando con una instalación local y creí que tenía dev-master en el de staging. Ese era el problema.

Se puede revisar si tienes esta situación, checando que en composer.json exista la línea
```
"openpay/magento2-banks": "1.3"
```
en lugar de la que debes tener
```
"openpay/magento2-banks": "dev-master"
```

La comparación de código de app/code/Openpay/Banks/Controller/Index/Webhook.php fue el que lo delató.

![image](https://user-images.githubusercontent.com/11946875/36119891-0604b30a-1007-11e8-884a-48789e5a5f23.png)

vs. 

![image](https://user-images.githubusercontent.com/11946875/36119922-1dea5d9e-1007-11e8-9ca5-4f920b166605.png)


Muchas gracias!

**Comment by QuiqueM** [comment]
Hola entonces no funciona de manera local ? quiseguardar cambios y me marco este error Something went wrong while saving this configuration: Could not connect with webhook service, verify URL

**Comment by fedebalderas** [comment]
Ese error se muestra cuando también esta instalado un plugin de pagos offline (SPEI o Pago en tiendas), ya que estos si ocupan de un webhook para que los pagos se confirmen y cambien el estatus de la orden de compra (ya que no son pagos que se completan en tiempo real). 

La cuestión es que cuando trabajas de forma local, Openpay trata de validar el webhook (la URL) y al ser el tuyo un ambiente local y no estar público en internet, Openpay no tiene modo de alcanzarlo y por ende no puede verificarlo.

Sin embargo para pago con tarjetas no ocupas un webhook y puede cerrar un flujo de pago completo o hacer pruebas con tarjetas que te devuelvan error, probar el 3D Secure, etc.
