### ISSUE TITLE
Empty or no Merchant ID provided

### ISSUE THREAD

**Issue by MarcoSantana** [open-pay/openpay-magento2-cards#11]
Hi. Everything seems to install properly but when I try to enable Card Payment I get 

`Empty or no Merchant ID provided
`
I already used my mechant_id , pk and sk provided by Openpay in my account.
But it seems to need the prodcution values also which I am not ready to get.
Is there a work around so I can run tests?
I am on Ubuntu 16 on DigitalOcean.

**Comment by fedebalderas** [comment]
Que tal @MarcoSantana, en realidad no necesitas las llaves productivas como mencionas. 

Sabes cual puede ser el problema y si es algo debemos de corregir, probablemente tienes también instalado algún otro plugin de Openpay (Pago en tiendas o SPEI) y cuando se da clic en guardar en realidad Magento manda la info de todos los forms de pago independientemente de cual tengas desplegado o no y probablemente en otro plugin de Openpay aunque no lo tengas como habilitado hace la validación de que requiere el merchant_id. 

Si es que si tienes otro plugin de Openpay instalado, intenta configurarle las llaves también y ver si esto le da solución.

**Comment by MarcoSantana** [comment]
Hola @fedebalderas : 
Ya seguí tus instrucciones y de hecho su hubo mejora. El tema ahora es con los webhooks (que según entiendo se generan automáticamente).
Recibo este error:
`Something went wrong while saving this configuration: The webhook with url http://167.99.175.65/openpay/index/webhook already exists
`
Pudieras por favor indicarme cómo solventarlo (ó ¿tengo que abrir otro issue?)
Gracias

**Comment by PhenomAmd** [comment]
> Que tal @MarcoSantana, en realidad no necesitas las llaves productivas como mencionas.
> 
> Sabes cual puede ser el problema y si es algo debemos de corregir, probablemente tienes también instalado algún otro plugin de Openpay (Pago en tiendas o SPEI) y cuando se da clic en guardar en realidad Magento manda la info de todos los forms de pago independientemente de cual tengas desplegado o no y probablemente en otro plugin de Openpay aunque no lo tengas como habilitado hace la validación de que requiere el merchant_id.
> 
> Si es que si tienes otro plugin de Openpay instalado, intenta configurarle las llaves también y ver si esto le da solución.

No entiendo porque nos obligam a instalar los 3 modulos es decir y espero no sonar grosero quien en su sano juicio pagaria comisión por un pago que haran en efectivo si bien el meotodo de paro no está mal porqie permite gestionqr pagos para personas que no quieren dqr datos etc con la ley de obrador es hasta inseguro para nosotros aceptar pahos de quien sea,  pero q su vez gracias a la ley y a la apertura de cuentas digitales es ilogico que digan "es que ni manejo tarjetaw" en lo personal no pienso usar pagos offline mediante tu plataforma me podrias decir como quito spei y la otra???

**Comment by roisdavila** [comment]
Me pasa lo mismo, instalé las ultimas versiones de Bancos, Tarjetas y Tiendas. Pero me pedia una clase que no tenía, entonces baje el Openpay/Data/Client.php que encontré en uno de los hilos de desarrollo. Funciona bien para Tarjetas pero no Para Bancos y Tiendas porque le faltan funciones. Donde puedo encontrar el Client.php mas reciente? o como puedo burlar este error sin esos módulos? 

Something went wrong while saving this configuration: Empty or no Merchant ID provided
