### ISSUE TITLE
No se crea webhook

### ISSUE THREAD

**Issue by LittaPanda** [open-pay/openpay-magento2-cards#13]
He instalado y configurado el modulo (openpay/magento2-cards) en magento 2.2.6 pero no veo ningún webhook generado en el portal de openpay.
Estoy en ambiente productivo.
Las operaciones han estado pasando, pero no se notifica al cliente.
Me podrias ayudar con los pasos para configurar esto?
Gracias de antemano.

**Comment by fedebalderas** [comment]
Que tal @LittaPanda, para el plugin de tarjetas no se utiliza un webhook ya que las transacciones y autorizaciones son en tiempo real, por ende manejamos los cambios de estatus sin un webhook. 

En teoría si la transacción es exitosa, la orden queda como pagada y marcada como processing, el envío de correo pues lo debería de hacer la tienda (Magento). Tus ordenes si quedan como te menciono?

P.D. Los webhooks si son utilizados en los plugins de pagos offline (Tiendas y SPEI).

**Comment by LittaPanda** [comment]
Hola @fedebalderas, gracias por tu pronta respuesta. 
Tuve un incidente en el que el servidor de magento2 se colgó y dejó la compra como en proceso de pago en el portal de OpenPay, sin embargo en el portal de magento2 (en el perfil del usuario) no se veia. Cabe mencionar que desde el portal de admin de magento2 si pudimos localizar la operación, pero al no tener como continuarla la cancelamos. 
Voy a verificar la configuración de magento2 por que no están llegando las notificaciones via email respecto al status de pago denegado desde OpenPay. (Fue por este motivo la curiosidad en los webhooks)
Con respecto a las compras autorizadas, esas si se notifican y pasan al estatus correspondiente.
Sigo con la investigación y si hay algún tema te lo consultamos.
Mil gracias.

**Comment by fedebalderas** [comment]
@LittaPanda Claro que si, sigo al pendiente de cualquier cosa. Voy a cerrar este issue, si algo se presenta igual solo levantas otro porfa. 

Saludos!
