### ISSUE TITLE
change the value requires_account "true" to "false"

### ISSUE THREAD

**Issue by patobp** [open-pay/openpay-magento2-cards#14]
openpay tells me that I have to make this change

change the value requires_account "true" to "false", but looking for all the code I can not find where this change of favor can be made if you could help me, thanks

**Comment by bohemio-rulo** [comment]
Tengo el mismo problema

**Comment by fedebalderas** [comment]
@patobp pero cual es el problema puntualmente? como mencionas es la instrucciones que se te dió pero debido a que?

**Comment by bohemio-rulo** [comment]
Esto se me envio al generar una orden espero ayude

Clientes con cuenta
​Estimado Comercio,

Se realizó la revisión del problema que nos comenta, observamos que el
registro de los clientes no fue realizado de forma correcta, ya que se
registraron con clientes con cuenta, y no como clientes catálogo. (
https://www.openpay.mx/docs/customers.html). Esta es la razón por la cual
los cargos recibidos, no se ven reflejados en la cuenta del comercio, ya
que el saldo está siendo abonado a la cuenta de los clientes.

La forma de solucionarlo, es aplicar un cobro de comisión (
https://www.openpay.mx/docs/api/#cobrar-comisi-n) por el total del saldo
que cada cliente tiene, esto para poder pasar esos montos a la cuenta de
comercio.

curl https://sandbox-api.openpay.mx/v1/mzdtln0bmtms6o3kck8f/fees \ -u
sk_e568c42a6c384b7ab02cd47d2e407cab: \ -H "Content-type: application/json" \

-X POST -d '{

"customer_id" : "dvocf97jd20es3tw5laz",   "amount" : 12.50,

"description" : "Cobro de Comisión",   "order_id" : "oid-1245" }'

Una vez hecho esto, se deben eliminar los clientes y dar de alta nuevamente
de forma correcta para evitar que el problema siga afectando.

Para que ya no sean creados clientes con cuenta en necesario cambiar el
valor requires_account “true” a “false”.

**Comment by bohemio-rulo** [comment]
> @patobp pero cual es el problema puntualmente?

Esto se me envio al generar una orden espero ayude

Clientes con cuenta
​Estimado Comercio,

Se realizó la revisión del problema que nos comenta, observamos que el
registro de los clientes no fue realizado de forma correcta, ya que se
registraron con clientes con cuenta, y no como clientes catálogo. (
https://www.openpay.mx/docs/customers.html). Esta es la razón por la cual
los cargos recibidos, no se ven reflejados en la cuenta del comercio, ya
que el saldo está siendo abonado a la cuenta de los clientes.

La forma de solucionarlo, es aplicar un cobro de comisión (
https://www.openpay.mx/docs/api/#cobrar-comisi-n) por el total del saldo
que cada cliente tiene, esto para poder pasar esos montos a la cuenta de
comercio.

curl https://sandbox-api.openpay.mx/v1/mzdtln0bmtms6o3kck8f/fees \ -u
sk_e568c42a6c384b7ab02cd47d2e407cab: \ -H "Content-type: application/json" \

**Comment by patobp** [comment]
> @patobp pero cual es el problema puntualmente?

Esto se me envio al generar una orden espero ayude

Clientes con cuenta
​Estimado Comercio,

Se realizó la revisión del problema que nos comenta, observamos que el
registro de los clientes no fue realizado de forma correcta, ya que se
registraron con clientes con cuenta, y no como clientes catálogo. (
https://www.openpay.mx/docs/customers.html). Esta es la razón por la cual
los cargos recibidos, no se ven reflejados en la cuenta del comercio, ya
que el saldo está siendo abonado a la cuenta de los clientes.

La forma de solucionarlo, es aplicar un cobro de comisión (
https://www.openpay.mx/docs/api/#cobrar-comisi-n) por el total del saldo
que cada cliente tiene, esto para poder pasar esos montos a la cuenta de
comercio.

curl https://sandbox-api.openpay.mx/v1/mzdtln0bmtms6o3kck8f/fees \ -u
sk_e568c42a6c384b7ab02cd47d2e407cab: \ -H "Content-type: application/json" \

**Comment by fedebalderas** [comment]
@patobp así es, en la última actualización del plugin se implementaron nuevas funcionalidades entre las cuales una de ellas tenía un bug, se omitía el parámetro que mencionan pusieras en false. Ayer este bug fue resuelto y se liberó una nueva actualización (te recomiendo actualices el módulo) y para darle solución o mover el saldo de las cuentas de clientes a tu cuenta de comercio si se tendría que realizar lo que te mencionan, realizar ese cobro de comisión a través de la API.

**Comment by patobp** [comment]
> @patobp así es, en la última actualización del plugin se implementaron nuevas funcionalidades entre las cuales una de ellas tenía un bug, se omitía el parámetro que mencionan pusieras en false. Ayer este bug fue resuelto y se liberó una nueva actualización (te recomiendo actualices el módulo) y para darle solución o mover el saldo de las cuentas de clientes a tu cuenta de comercio si se tendría que realizar lo que te mencionan, realizar ese cobro de comisión a través de la API.

gracias lo actualizo y te comento
