### ISSUE TITLE
Frontend Checkout page blank after enabled this payment.

### ISSUE THREAD

**Issue by patellalit** [open-pay/openpay-magento2-cards#16]
I installed extension in my magento 2 store. Once I added sandbox detail and enable this payment option.
Frontend after logged with username password checkout page is blank. 
Without logged in processed with guest user. Its working fine.
After disabled this payment option. Checkout page is working fine.
I also installed Bank transfer and cash payment. Its working fine. Only issue with card payment.

![image](https://user-images.githubusercontent.com/244568/57878201-24f3c280-7837-11e9-97b3-e5a0fcc68dc6.png)

![image](https://user-images.githubusercontent.com/244568/57878333-6edca880-7837-11e9-9982-98c33789d053.png)
![image](https://user-images.githubusercontent.com/244568/57878371-7ef48800-7837-11e9-8729-7ff9e518fffe.png)

**Comment by fedebalderas** [comment]
Hye @patellalit, just to have the whole context:

- Which version of Magento do you have?
- Which version of our plugin do you have?
- Did you take look into your Magento logs to check if something is crashing?

**Comment by fedebalderas** [comment]
@patellalit Do you have enabled the developer mode?

**Comment by patellalit** [comment]
@fedebalderas Thanks for reply.

Magento ver. 2.3.1
Plugin ver. 
"openpay/magento2-cards": "dev-master"

Do you have enabled the developer mode?
Yes

**Comment by fedebalderas** [comment]
@patellalit I recommend you to follow the instructions: https://github.com/open-pay/openpay-magento2-cards#instalaci%C3%B3n

`composer require openpay/magento2-cards:~2.3.3`

You'll need to install the package with version number, because dev-master points to a different Openpay SDK version than v2.3.3.

**Comment by patellalit** [comment]
I run this command. Module updated without any error. But still getting error. I already clear cache, setup upgrade.

`composer require openpay/magento2-cards:~2.3.3`

**Comment by andresadanmx** [comment]
Tengo el mismo problema:
Magento: ver. 2.3.2
Plugin: 2.4.*
Theme Magento Luma

También lo probé en un Magento 2.2.9 y está con el mismo error. Solo sucede con Openpay Cards.

¿Haya algo que se pueda hacer para solucionar el problema?
