### ISSUE TITLE
Error al realizar pago con tarjeta affiliation.name is required

### ISSUE THREAD

**Issue by valen92** [open-pay/openpay-magento2-cards#17]
Hola, al tratar de realizar pagos con tarjeta a tráves de 3d-secure sake ek siguiente error affiliation.name is required

![image](https://user-images.githubusercontent.com/6044466/61567678-10ee5c00-aa46-11e9-8597-12257088a21a.png)

**Comment by fedebalderas** [comment]
@valen92 Estas utilizando la solución de BBVA, cierto?

**Comment by fedebalderas** [comment]
@valen92 Oye adicional a esto, veo que estas utilizando una implementación en Java y no tiene relación con el plugin de Magento2 (PHP)

**Comment by valen92** [comment]
@fedebalderas Si es la solución de BBVA

**Comment by fedebalderas** [comment]
@valen92 ese es el tema, este plugin esta probado 100% únicamente contra los servicios de Openpay, la solución de BBVA a pesar de tener similitudes no comparte al 100% flujos, datos de entrada y salida, por eso es que no te esta funcionando. En este caso o por el momento tendrías que hacer la implementación por tu parte: https://docs.ecommercebbva.com/
