### ISSUE TITLE
La opción de pago con tarjeta no se muestra en el checkout

### ISSUE THREAD

**Issue by lgarridoj** [open-pay/openpay-magento2-cards#2]
Habilité las 3 opciones de pago (banks, stores, cards) pero no se muestra la opción de pago con tarjeta en el checkout.

(También me marca un error al guardar la configuracion en el panel de admin pero supongo que se debe a estar en ambiente local)

Magento 2.0.4
PHP 5.6

![payment-checkout](https://cloud.githubusercontent.com/assets/8398744/14928433/91b25a58-0e1d-11e6-935d-3bc412db3d74.jpg)

![error-magento2-a](https://cloud.githubusercontent.com/assets/8398744/14928483/dcbb9e74-0e1d-11e6-9b93-9eb0982dab80.jpg)

**Comment by fedebalderas** [comment]
Que tal Luis,

Como mencionas, el error que te arroja es por el ambiente local que estas manejando. Te respondí el correo que me enviaste a ver si me pudieras hacer llegar la impresión de pantalla que te menciono.


Saludos!

**Comment by fedebalderas** [comment]
Se realiza una previa validación de la existencia de la propiedad addresses en el objeto window.checkoutConfig.customerData de Magento en el siguiente archivo: https://github.com/open-pay/openpay-magento2-cards/commit/12032159cefe0630e07b8baec95ac11f1fc60edc#diff-6240df53a3d487250d1298532fe46e7c

Con esta modificación se le da solución al problema.
