### ISSUE TITLE
Dudas instalación

### ISSUE THREAD

**Issue by poncho0193** [open-pay/openpay-magento2-cards#22]
**Hola perdón por lo extenso del tema pero he iniciando la instalación nuevamente.**

He tenido errores durante la instalación, buscando en internet logré habilitar la extensión pero al realizar un cargo con un usuario registrado mostraba el siguiente error
![openpay error](https://user-images.githubusercontent.com/24686959/77010888-4ed2b580-6930-11ea-9240-77891c8315d2.PNG)

Supongo que con los errores de la instalación no se logró instalar la base de datos.
Iniciando nuevamente con la instalación no he logrado encontrar porqué el comando de git no lo reconoce, tengo instalado el git, 
![instalacion openpay](https://user-images.githubusercontent.com/24686959/77009281-42992900-692d-11ea-9178-b1848720f213.PNG)
ahora entiendo que ahí ya se realizó la descarga de la extensión por otro método o no?

Y para los paquetes obsoletos simplemente decidí continuar con los siguientes pasos de la instalación, no sé si desde ahí comienza mi problema con la instalación.
 
![instalacion openpay2](https://user-images.githubusercontent.com/24686959/77009433-88ee8800-692d-11ea-8ce3-2131d07a9d9e.PNG)

Continué con los pasos de la instalación y una vez finalizado el proceso y recargar la página de magento aparece
![instalacion openpay3](https://user-images.githubusercontent.com/24686959/77009754-17630980-692e-11ea-8a98-fe7b6277e19c.PNG)
buscando encontré que con los siguientes comandos se soluciona

php bin/magento deploy:mode:set developer
php bin/magento module:enable --all
php bin/magento cache:clean

ejecuté los comandos y ahora en el navegador carga 
![instalacion openpay5](https://user-images.githubusercontent.com/24686959/77010289-1d0d1f00-692f-11ea-9504-6ece45058ac6.PNG)

siguiendo las instrucciones de " Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory."

al ejecutar el comando la consola muestra 
![instalacion openpay4](https://user-images.githubusercontent.com/24686959/77010419-5776bc00-692f-11ea-845c-94b922f1794d.png)
no sé si ahí es donde debería estar la data para la extensión del openpay.
al final el comando termina con
![instalacion openpay6](https://user-images.githubusercontent.com/24686959/77011257-1089c600-6931-11ea-8c6c-c19a9074d7ac.PNG)
con el nothing to import, no sé a que hace referencia ni cuán importante sea.

Refrescando la página vuelvo al error que muestra la primer imagen del tema.  y [acá abrí un tema al respecto](https://github.com/open-pay/openpay-magento/issues/11) donde vuelvo a hacer los mismos cambios en el archivo mencionado y obtengo los mismos resultados. Dado que se volvó un loop, espero que me puedan ayudar.

**Comment by fedebalderas** [comment]
@poncho0193 a lo que veo, supongo no desintalaste el paquete previo a seguir los pasos que te comenté en el otro issue, ya que ahí claramente hace el downgrade del paquete (primer pantalla) en lugar de instalar desde 0, lo segundo que observo y no hace sentido tampoco es que cuando se trata de instalar el paquete de tarjetas también esta intentando instalar el paquete de tiendas, eso no tiene sentido alguno. 

Como te comentaba en el otro issue, elimina paquetes (tarjetas, tiendas, bancos), limpia cache de composer y sigue las instrucciones.

**Comment by poncho0193** [comment]
Hola que tal, hice lo que comentas, ahora durante la instalación ya no hizo lo del downgrade, tampoco salió que no reconoce el comando git, solo lo de "Package ... is abandoned..." y cuando vuelvo a iniciar el apache y recargo la página de administración de magento y mi tienda carga todo bien el problema sigue siendo cuando quiero hacer un pago con un usuario registrado.
sigue apareciendo:

1 exception(s):
Exception #0 (Magento\Framework\Validator\Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.openpay_customers' doesn't exist, query was: Select * FROM openpay_customers WHERE customer_id = "2" limit 1

**Comment by poncho0193** [comment]
**Actualización**

Buscando en mi base de datos me di cuenta que si existe la tabla pero lleva **"ss_"** antes del nombre **"openpay_customers"**  alguna idea de porqué la extensión va y busca la tabla sin el **"ss_"** antes de la palabra y dónde puedo corregirlo? 


Para probar cree una tabla con el nombre **"openpay_customers"** y obviamente funciona lo raro es que cuando realizo el proceso del pago y hago select a la tabla **"openpay_customers"** no hay nada pero en la tabla **"ss_openpay_customers"** si 
![tabla openpay](https://user-images.githubusercontent.com/24686959/77093320-6eb9b600-69d0-11ea-87b0-25043b8b5f42.PNG)
![consulta openpay](https://user-images.githubusercontent.com/24686959/77093321-6f524c80-69d0-11ea-8651-cac77adde8eb.PNG)
