### ISSUE TITLE
 error_code: 1003 en la llamada POST /v1/{merchand_id}/charges

### ISSUE THREAD

**Issue by almaochoa** [open-pay/openpay-magento2-cards#23]
Al querer procesar un cargo con token, con la siguiente llamada

![image](https://user-images.githubusercontent.com/65498952/82152046-6b05ac80-9824-11ea-8af0-c461cd6fe871.png)

estoy recibiendo

![image](https://user-images.githubusercontent.com/65498952/82152064-7bb62280-9824-11ea-88a0-4dd760d7e9cf.png)

Estoy en modo sandbox y en la llamada previa para obtener el token, tengo éxito.
Estoy comparando los parámetros que envío con los de la documentación de la API y no veo que me haga falta algún valor, puesto que el merchand_id va en el URL

Hice pruebas con tarjeta de crédito real y con algunas de las de pruebas de https://www.openpay.mx/docs/testing.html

Espero sus comentarios :D

**Comment by fedebalderas** [comment]
@almaochoa me da la impresión que tiene que ver con la configuración que tiene tu cuenta de comercio, es decir, no es tema como tal del plugin. Te podría recomendar que contactes al equipo de soporte (soporte@openpay.mx) y les menciones el error que presentas para que puedan hacer el ajuste en tu cuenta de comercio.
