### ISSUE TITLE
The card charge is on a final status

### ISSUE THREAD

**Issue by PonchoDlr** [open-pay/openpay-magento2-cards#38]
Hola que tal cuando quiero procesar una orden recibo el siguiente mensaje "The card charge is on a final status" anteriormente recibía el mensaje de "Empty or no Merchant ID provided" y no puedo dar salida a mis órdenes de compra en magento 2. 

Alguna solución que sugieran o quizá alguna configuración que esté pasando por alto?

Cabe mencionar que estoy configurando los métodos de pago para distintas tiendas en una sola instalación de magento 2, al guardar los datos de pago recibí el siguiente mensaje 
![image](https://user-images.githubusercontent.com/73364097/98301801-fb75ac00-1f80-11eb-92b6-7602202e5dd2.png)

Y el siguiente mensaje es el que recibo al intentar capturar el pago de la orden
![image](https://user-images.githubusercontent.com/73364097/98301875-1c3e0180-1f81-11eb-9faa-1d469dac15ba.png)

**Comment by hcontreras** [comment]
Qué tal, @PonchoDlr 

Desconozco a qué se refiere el primer error que reportas, pero, sobre el segundo te puedo asegurar que a la hora de guardar tus cambios en la pantalla de Payment Methods, tienes algún método de pago que intenta generar un nuevo WebHook en su plataforma.

Este error es común cuando integras Connekta. Tienes que entrar al panel de Connekta, borrar o deshabilitar tu actual Webhook, guardar cambios y luego volver a Magento y guardar tus cambios. Solo así ya no te saldrá ese mensaje.

Saludos.

**Comment by jose-openpay** [comment]
Buen día @PonchoDlr 

El mensaje que se presenta al momento de guardar la configuración sobre el webhook, es precisamente un error que muestra el plugin al intentar crear nuevamente este webhook dentro del dashboard Openpay. No es un error, sino indica que ya se encuentra un webhook registrado con está url. 

Si usted tiene varias tiendas integradas en una misma plataforma de Magento 2, contacte directamente a  soporte@openpay.mx para dar seguimiento a este tema y brindarle una solución. 

En cuanto al segundo error, si usted tiene configurados cargos directos, al concluir el flujo de pago completo por parte del usuario final, la transacción en Openpay pasará a un estatus de cargo completado. No es necesario procesar el pago dentro de su Dashboard de Magento 2. 

Quedo atento a sus comentarios, Saludos .
