### ISSUE TITLE
Wrong Setup

### ISSUE THREAD

**Issue by shinesoftware** [open-pay/openpay-magento2-cards#4]
I am trying to install OpenPay by Composer:

    $ composer require openpay/magento2-cards

this is the error:

`Autoload error: Module 'Openpay_Cards' from '/var/www/html/magento2.local/app/code/Openpay/Cards' has been already defined in '/var/www/html/magento2.local/vendor/openpay/magento2-cards'.
`

How to solve it ?

**Comment by fedebalderas** [comment]
Hi @shinesoftware, i tried to replicate this issue but i can't... it works fine to me.

Try to remove this folder **/var/www/html/magento2.local/vendor/openpay/magento2-cards** and then run **composer update** 

Best regards!

![screen shot 2016-09-21 at 11 28 41 am](https://cloud.githubusercontent.com/assets/5208431/18719851/b4719764-7fee-11e6-89ed-7b1dfd64f118.png)

**Comment by shinesoftware** [comment]
![composer](https://cloud.githubusercontent.com/assets/1553035/18756001/7f8b9238-80ee-11e6-9907-0818ce9c8110.png)

**Comment by fedebalderas** [comment]
Did you still have problems? I can't see the error that you mentioned before.

Best regards!

**Comment by shinesoftware** [comment]
I am testing it and now it works! 
Thanks @fedebalderas
