### ISSUE TITLE
Después de habilitar el modo de producción, el checkout de magento sigue llamando a la url de sandbox

### ISSUE THREAD

**Issue by lgarridoj** [open-pay/openpay-magento2-cards#6]
He deshabilitado el modo Sandbox e ingresé las credenciales de producción. Sin embargo, al momento de hacer clic en "confirmar compra", no pasa nada, y el monitor de red muestra que se está llamado a la URL **sandbox**-api.openpay.mx y la compra no se completa.
Adjunto imágenes.
![produccion-claves](https://cloud.githubusercontent.com/assets/8398744/23767854/bb88a932-04cf-11e7-9fe3-9daf53d97bc0.png)
![produccion-claves-2](https://cloud.githubusercontent.com/assets/8398744/23767856/bb8c6018-04cf-11e7-82e4-ba2d27eeb259.png)
![error-checkout](https://cloud.githubusercontent.com/assets/8398744/23767855/bb8b4e9e-04cf-11e7-8ef4-7c6a9de3f3eb.png)

**Comment by fedebalderas** [comment]
El problema es al actualizar la dependencia vía Composer, no descarga las últimas modificaciones (fixes).

La actualización correspondiente que soluciona este problema es:
https://github.com/open-pay/openpay-magento2-cards/commit/1b8660c8c2287fd067cf22b44cc47f39d905f435

Adicional a ello tampoco descarga este segundo fix:
https://github.com/open-pay/openpay-magento2-cards/commit/2a16ca95ced8366f684e3d5ffa3644d3f3ba5aec

Se revisará el webhook de Packagist.
