### ISSUE TITLE
Los métodos no se ven en el frontend al cambiar de servidor y url

### ISSUE THREAD

**Issue by eliacimdavila** [open-pay/openpay-magento2-cards#7]
Buenos días.

Instalamos los tres métodos de pago:

**Openpay_Banks
Openpay_Cards
Openpay_Stores**

Primero en un ambiente de pruebas local, y los tres son listados de manera correcta en el checkout:

![openpay1](https://cloud.githubusercontent.com/assets/21063809/26214574/808b1764-3bc2-11e7-89ba-c995efb5efdb.JPG)

Sin embargo, cuando subimos el sitio a otro servidor de preproducción para que se pudieran hacer pruebas desde afuera y con SSL, los métodos dejaron de listarse:

![openpay2](https://cloud.githubusercontent.com/assets/21063809/26214621/b156d7ac-3bc2-11e7-9ed0-7506186e579b.JPG)

No se hizo ningún cambio en la configuración ni en los archivos, todo es igual (incluyendo el ID y las Keys). Seguimos aun con las llaves de Sandbox. Las únicas diferencias son:

1) Es otro servidor
2) Es una URl diferente (no sé si estoy influya)
3) Tiene encendido el cache (pero ya probe deshabilitarlo y borrarlo, y siguen sin aparecer)

¿Podrían darme una pista de qué es lo que debería de revisar?

En el composer.json, están listados de esta forma:

> "openpay/magento2-stores": "^1.2",
> "openpay/magento2-cards": "^1.3",
> "openpay/magento2-banks": "^1.2",

Intente tambien darle un **composer update**, pero no hubo ningún cambio.

Gracias

**Comment by fedebalderas** [comment]
Que tal @eliacimdavila, pues lo primero que yo haría sería eso... actualizar Composer y limpiar cache. Pero no te arroja algún error Composer o en su defecto algún error en el log de Magento?

Has intentado habilitar los plugins con el comando:
php bin/magento module:enable Openpay_Cards --clear-static-content

Y revisa si en este archivo los tienes habilitados:
app/etc/config.php
![screen shot 2017-05-18 at 5 15 21 pm](https://cloud.githubusercontent.com/assets/5208431/26225617/a15f8134-3bed-11e7-8434-94ecd144f973.png)

Me cuentas...

**Comment by eliacimdavila** [comment]
Hola @fedebalderas gracias por responder. Te respondo:

> Pero no te arroja algún error Composer o en su defecto algún error en el log de Magento?

Composer solo me aroja lo siguiente:

```
Loading composer repositories with package information                                                                                      
Updating dependencies (including require-dev)         
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Generating autoload files
```
El log de Magento no me marca nada al correr composer. El único un error que sí me está apareciendo en log, que ocurre al intentar actualizar algun parametros en el admin (que no sé si pudiera estar relacionado con esto) es éste:

`main.CRITICAL: Exception message: The webhook with url http://mosereco.nextmp.net/openpay/index/webhook already exists`

> Has intentado habilitar los plugins con el comando:
> php bin/magento module:enable Openpay_Cards --clear-static-content

Al correr el comando, sólo me arroja:

`No modules were changed.`

> Y revisa si en este archivo los tienes habilitados:
> app/etc/config.php

Sí, si aparecen listados y habilitados:

![openpay7](https://cloud.githubusercontent.com/assets/21063809/26227058/8e0f889c-3bf5-11e7-9557-ad8dc4f37c9b.JPG)

De hecho si aparecen las opciones en el admin de cada uno, y están habilitados como en desarrollo, pero no se ven en el frontend:

![openpay3](https://cloud.githubusercontent.com/assets/21063809/26227063/9db2fa0e-3bf5-11e7-9bca-52bc1cbf20e0.JPG)

**Comment by fedebalderas** [comment]
En teoría ese error es cuando intenta generar el webhook en Openpay pero pues ya existe (según)... pero no tendría ningún impacto con que se muestren o no las formas de pago.

Revisé tu tienda hasta el checkout pensando que podría encontrar algún error tal vez con JS pero no... mándame un correo porfa federico.balderas@openpay.mx y si pudieras darme acceso a tu backoffice para revisar algo porfa.

Saludos!

**Comment by richycorre** [comment]
Hola federico como estas, yo presento el mismo error solo me sale el sistema de apgos de tc y no parecen los demas. quepodra pasar? o como se puede arreglar=?

**Comment by fedebalderas** [comment]
@richycorre verifica que tu moneda base sea el peso mexicano, de otro modo "Pagos en tienda" y "SPEI" no se van a mostrar debido a que únicamente soportan MXN como moneda de pago. Por otro lado pago con TC soporta USD y MXN, muy probablemente tengas USD como moneda base de tu tienda.
