### ISSUE TITLE
Unclosed '{' on line 39#0 vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()

### ISSUE THREAD

**Issue by eliacimdavila** [open-pay/openpay-magento2-cards#76]
Al momento de instalar la última versión del Módulo de Openpay Cards, al momento de querer correr cualquier comando de Magento regresa el siguiente error:

> The command "php ./bin/magento module:enable --all --ansi --no-interaction"
>         W:    failed. Unclosed '{' on line 39#0 /app/vendor/composer/ClassLoader.php(428
>         W:   ): Composer\Autoload\includeFile('/app/vendor/com...')
>         W:   #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Openpay\\
>         W:   Cards\\M...')

Luego de revisar el código, detecté que el error lo origina el archivo Model/Payment.php:

https://github.com/open-pay/openpay-magento2-cards/blob/master/Model/Payment.php

Hace falta una "}" al final del archivo:

![image](https://user-images.githubusercontent.com/21063809/197630828-88a98724-10c8-4829-b697-370ebb87186d.png)

Y aunque en mi local lo pude corregir manualmente, al querer subirlo a Magento Cloud no me toma el cambio. Supongo el archivo debe ser corregido desde el repositorio para que lo tome.

**Comment by jose-openpay** [comment]
Buen día @eliacimdavila 

Se sube corrección en el siguiente merge #78, gracias por compartir el fix

Saludos Equipo Openpay !
