### ISSUE TITLE
Error al guardar credenciales de Openpay

### ISSUE THREAD

**Issue by luisfernando001** [open-pay/openpay-magento2-cards#8]
Buen día, en Magento 2.1.7 cuando intento de guardar las credenciales de Openpay en Métodos de Pago me arroja el siguiente error:

Something went wrong while saving this configuration: Expected 200 response from http://site-path/openpay/index/webhook but was 302 - Found

Y dentro de esa liga veo el siguiente error:

Exception #0 (Exception): Notice: Trying to get property of non-object in path/html/app/code/Openpay/Banks/Controller/Index/Webhook.php on line 40

Quedo al pendiente, gracias y saludos.

**Comment by fedebalderas** [comment]
Que tal @luisfernando001, 

De forma transparente para los administradores se crea un webhook, esta es una URL sobre tu domino que siempre esta "escuchando" las confirmaciones de pago de tus transacciones, sin embargo Openpay trata de validar la URL del webhook pero en este caso en lugar de recibir un código 200 (éxito), esta recibiendo un redireccionamiento (302). Cual es la URL de tu sitio? Utilizas SSL? Siento que podría ir por ahí, esta tratando de registrar tu sitio como http cuando tal vez tienes un https.

**Comment by luisfernando001** [comment]
Muchas gracias por la pronta respuesta @fedebalderas , en efecto utilizo SSL, la URL de mi sitio es la siguiente: http://bit.ly/2rAJfxZ   (muestro en formato bitly por seguridad) 
Saludos

**Comment by fedebalderas** [comment]
Te paso mi correo y lo revisamos por ahí... federico.balderas@openpay.mx

**Comment by fedebalderas** [comment]
Actualización de composer.json apuntando a "dev-master" de cualquiera de los 3 plugins de Openpay para Magento2
