### ISSUE TITLE
Error al guardar configuración

### ISSUE THREAD

**Issue by edcg** [open-pay/openpay-magento2-cards#9]
Hola, 

Cuando intento guardar la configuracion de openpay me está saliendo el error Something went wrong while saving this configuration: Expected 200 response from http://mydomain/openpay/index/webhook but was 503 - Service Unavailable. El log en open pay tiene como respuesta: 
{
    "category": "request",
    "description": "Expected 200 response from http://mydomain/openpay/index/webhook but was 503 - Service Unavailable",
    "http_code": 502,
    "error_code": 6003,
    "request_id": "7eed180e-cd3c-421d-9c22-1eb7a3d3182f"
}

¿Cuál podría ser la causa de este error? Veo que hay otros similares de otros usuarios.

**Comment by fedebalderas** [comment]
@edcg Como puedes ver Openpay trata de validar la URL del webhook que va a estar "escuchando" en tu sitio. Si literal ese es el error que te arroja como puedes ver es una URL que nunca se va a alcanzar desde internet. 

En ambientes locales siempre te va a ocurrir esto hasta que lo tengas publicado en línea.


Saludos!

**Comment by edcg** [comment]
Pero es que no es un ambiente local puse "mydomain" para no poner mi dominio real pero si está publicado (en lugar de mydomain el error tiene a mi dominio). Lo único fue que acabo de hacer una migración entonces el servidor cambió.

**Comment by fedebalderas** [comment]
Entonces hay que revisar el log de tu tienda para saber a que se debe el 503, podríamos simular la petición de Openpay desde un cliente Rest. Si quieres lo vemos por correo para que me puedas compartir tu dominio.

**Comment by fasaro** [comment]
hola @fedebalderas  estoy presentando el siguiente problema si me puedes ayudar, ya que NO estoy recibiendo notificaciones de pagos (efectivo y transferencias) gracias!

    "category": "request",
    "description": "The webhook with url https://misitio.com/openpay/index/webhook already exists",
    "http_code": 409,
    "error_code": 6001,
    "request_id": `"61b97318-ecb3-492f-83ed-11c5674a3abe"

**Comment by fedebalderas** [comment]
@fasaro en realidad ya tienes el webhook creado, eso es bueno. Igual solo para validar que este verificado debes de entrar a tu cuenta de Openpay (no sé si esto sea en sandbox o producción) y vayas al apartado de configuración y por ahí deberás de ver los webhook registrados y verificados.

Lo segundo sería preguntarte, tienes algún caso puntual de una compra con pago en tiendas o SPEI que se haya concretado y que el estatus de la orden en Magento no haya cambiado de "pending"? De ser así podrías revisar la fecha de pago de esa transacción en Openpay y revisar en el log de tu tienda (en ese día a esa hora) para ver que pudo pasar en el webhook, como ves?

**Comment by LittaPanda** [comment]
Hola @fedebalderas,
Estoy experimentando un problema con el modulo de tarjetas.
Cada vez que intento guardar la configuración me sale este error:
"Algo salió mal al guardar esta configuración: The webhook with url %s already exists"
Verifique el log y tengo lo siguiente:
https://gist.github.com/LittaPanda/45ebba451b985cd9b3f013ca77e2d3bd
¿Me podrias auxiliar con esta situación?
Desafortunadamente no pasa ningun cobro. Nos comunicamos con la gente de soporte de OpenPay y nos comentan lo siguiente:
"Queremos comentarle que revisando el listado que nos envía y revisando en el Dashboard todas las transacciones están fallidas y rechazadas por el sistema antifraude, al revisar los logs encontramos que no se esta agregando la URL de redireccionamiento al cliente para que el mismo pueda ingresar el código de confirmación de venta, que significa esto que al ingresar este medio de pago no quedo bien configurado desde un principio en este caso va a ser necesario que su desarrollador lo verifique y agrege la propiedad 3d security, para que sea instalado correctamente. "
En su momento se hicieron pruebas y todas salieron correctas, de hecho tengo algunas transacciones con proceso exitoso. 

Como información adicional te comento que se realizó un cambio en la propiedad "¿Cómo procesar el cargo?". Cambiamos de "3D Secure" a "Autenticación selectiva". 
Aún devolviendo el valor inicial nos arroja el error.
Agradezco tu atención de antemano.

**Comment by fedebalderas** [comment]
@LittaPanda que onda... son 2 cosas a como yo lo veo:

1.- El error en realidad es un warning, no pasa nada... solo es un mensaje de que el webhook en Openpay ya existe y eso es bueno, esto se arroja porque cada vez que se guarda algo en el módulo de pagos se trata de crear el webhok, puedes hacer caso omiso.

2.- Me da la impresión que tu comercio debe de estar forzado a usar 3D secure, por eso cuando usas autenticación selectiva no funciona de forma correcta. Podrías validar con el equipo de soporte si tu comercio tiene este forzado, de ser así no podrás usar autenticación selectiva. 

Saludos!

**Comment by LittaPanda** [comment]
Gracias @fedebalderas !!! Siempre tan pronto en tus respuestas :)
Lo checare directamente con soporte dándoles tu respuesta como punto de partida.
Saludos.

**Comment by BethRC** [comment]
Hola estoy tratando de agregar una url par webhook en la configuración de mi cuenta en sandbox, me manda este mensaje de error
  
- No hay respuesta en la Sesión actual, tiempo finalizado. Iniciar Sesión. (en esté caso si tengo la sesión activa).

y en ocaciones manda este otro:

- Fue imposible agregar el nuevo Webhook.  Verifique sus datos.

Podrían ayudarme no se que es lo que estoy haciendo mal

**Comment by fedebalderas** [comment]
@BethRC podrías adjuntar unas impresiones de pantalla porfa? Como que ando medio perdido con lo que comentas.

Por cierto te comento, para el plugin de tarjetas no es necesario agregar un webhook en Openpay ya que la notificación de estado es en el momento, es decir, pasa o no pasa. Caso contrario con los pagos en tienda y SPEI donde tiempo después el usuario aplica el pago.

**Comment by BethRC** [comment]
Disculpa al parecer también me confundí un poco estoy integrando pagos con tarjeta pero no estoy  usando el plugin de tarjetas magento.

De todas formas te dejo las capturas de pantalla de los errores, espero que puedas ayudarme.

![openpay](https://user-images.githubusercontent.com/58541250/70262399-e6cdda00-1759-11ea-8f17-fbf533f0cdf9.png)
![pagos open pay](https://user-images.githubusercontent.com/58541250/70262405-e9303400-1759-11ea-88a1-13d278ed54b3.png)

**Comment by richycorre** [comment]
Hola Fedebaldera como estas? soy ricardo de colombia, estoy intentando instalar opnpay, estoyen el sandbox, pero lastimosamente no me funciona.  1) magneto arroja un error al guardar donde dice que el webhook already exists, 2) instalamos todos los medio de pagos pero en el checkout solo sale pago con tarjeta y 3) ingreso las tarjetas de pruba y no pasa la transacción, dice error 0 la petición no puede ser procesada. ya no se que hacer???

**Comment by fedebalderas** [comment]
@richycorre 

1) El "error" del webhook es más un warning de que ya existe el webhook pero no pasa nada, de hecho así podríamos corroborar que el webhook ya existe y eso es bueno. Lo del pago con tarjeta tal vez sea por el tipo de moneda configurado. 

2) Te respondí en el otro issue pensando que eras de México, no sabía que estabas usando magento para Colombia. De ser así verifica que tu moneda base de la tienda sea el peso colombiano.

3) Revisaste los logs de tu tienda para checar el stacktrace de la excepción? también deberías de checar los logs del dashboard de Openpay para ver si la petición llega hasta Openpay o si se queda en tu server y nunca sale.
